#!/usr/bin/python3

import create_embedding_and_features
create_embedding_and_features.make_percent_training_feature_file()
create_embedding_and_features.make_percent_dev_feature_file()
create_embedding_and_features.make_percent_test_feature_file()
create_embedding_and_features.make_part_training_feature_file()
create_embedding_and_features.make_part_dev_feature_file()
create_embedding_and_features.make_part_test_feature_file()

# import build_model
# build_model.train_and_run("part", ada=True)
